//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDataSet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientDataSet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;ROW&gt;
        ///    &lt;CustNo&gt;1221&lt;/CustNo&gt;
        ///    &lt;Company&gt;Kauai Dive Shoppe&lt;/Company&gt;
        ///    &lt;Addr1&gt;4-976 Sugarloaf Hwy&lt;/Addr1&gt;
        ///    &lt;Addr2&gt;Suite 103&lt;/Addr2&gt;
        ///    &lt;City&gt;Kapaa Kauai&lt;/City&gt;
        ///    &lt;State&gt;HI&lt;/State&gt;
        ///    &lt;Zip&gt;94766-1234&lt;/Zip&gt;
        ///    &lt;Country&gt;US&lt;/Country&gt;
        ///    &lt;Phone&gt;808-555-0269&lt;/Phone&gt;
        ///    &lt;FAX&gt;808-555-0278&lt;/FAX&gt;
        ///    &lt;TaxRate&gt;8.5&lt;/TaxRate&gt;
        ///    &lt;Contact&gt;Erica Norman&lt;/Contact&gt;
        ///    &lt;LastInvoiceDate&gt;1995-02-02T01:05:03+01:00&lt;/LastInvoiceDate&gt;
        ///  &lt;/R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientDataSet1NET {
            get {
                return ResourceManager.GetString("ClientDataSet1NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;ROW&gt;
        ///    &lt;NAME&gt;Angel Fish&lt;/NAME&gt;
        ///    &lt;SIZE&gt;2&lt;/SIZE&gt;
        ///    &lt;WEIGHT&gt;2&lt;/WEIGHT&gt;
        ///    &lt;AREA&gt;Computer Aquariums&lt;/AREA&gt;
        ///    &lt;BMP&gt;AQAAAfY+AABCTfY+AAAAAAAAdgAAACgAAADIAAAAoAAAAAEABAAAAAAAgD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC/AAC/AAAAv78AvwAAAL8AvwC/vwAAwMDAAICAgAAAAP8AAP8AAAD//wD/AAAA/wD/AP//AAD///8AAA7u4CoqKgDu7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u4iIgAAKiogDu7u7u7u7u7u7u7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientDataSet2NET {
            get {
                return ResourceManager.GetString("ClientDataSet2NET", resourceCulture);
            }
        }
    }
}
